name: Coverage Upload

on:
  push:
    branches: [main]
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: "pnpm"

      - name: Install
        run: pnpm install --frozen-lockfile

      - name: Build
        run: pnpm build

      - name: Run tests (generate coverage)
        run: pnpm test

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v4
        with:
          files: |
            **/coverage/lcov.info
          fail_ci_if_error: false
          # token: ${{ secrets.CODECOV_TOKEN }} # uncomment if repo is private
