name: PR Validation

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read

jobs:
  validation:
    name: Test and Lint
    runs-on: ubuntu-latest
    timeout-minutes: 15
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v5
        with:
          fetch-depth: 0

      - name: Setup pnpm
        uses: pnpm/action-setup@v4

      - name: Setup Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: "pnpm"

      - name: Install Dependencies (all workspace packages)
        run: pnpm -r install --frozen-lockfile

      - name: Build (workspace root)
        run: pnpm build

      - name: Type Check (workspace root)
        run: pnpm check-types

      - name: Lint (workspace root)
        run: pnpm lint

      - name: Format Check (workspace root)
        run: pnpm fmt

      - name: Test (workspace root)
        run: pnpm test
